services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ${SRC_PATH}:/var/www/html/src:cached
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db

  db:
    image: ${MYSQL_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: